options:
  formatter: stylish
  merge-default-rules: true

rules:
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  force-attribute-nest:
    - 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  no-color-literals: 1
  # This the unqualified attributes sass-lint rule is wrong, disabling.
  # Source: https://github.com/CSSLint/csslint/issues/237
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  property-sort-order: 0
  variable-name-format:
      - 1
      -
        convention: hyphenatedbem
